version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./php:/var/www/html
      - image_volume:/var/www/html/images
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./php:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword  # La contraseña root de MySQL
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
  image_volume:
